---
namespace: chatwoot

stack:
  defines: process-group
  metadata:
    name: chatwoot
    shortname: Chatwoot
    description: |
      Chatwoot is a powerful and intuitive customer engagement platform that enables businesses to communicate with their customers seamlessly across multiple channels.

      With Chatwoot, businesses can manage all their customer conversations in one place, including email, social media, and messaging apps. The platform offers a range of features, including automated responses, chatbots, and real-time analytics, to help businesses improve their customer experience and increase customer satisfaction.

      Chatwoot is easy to set up and use, making it an ideal solution for businesses of all sizes looking to streamline their customer
      engagement processes.

      To start properly you need to run custom action: `monk do chatwoot/chatwoot-rails/prepare-db`
    website: https://www.chatwoot.com/
    publisher: monk.io
    icon: https://camo.githubusercontent.com/778ffdc9c0cb0bf52e04ffc22f3d392f028ceedc0f60c0e74741aac7c4375eb4/68747470733a2f2f73332e75732d776573742d322e616d617a6f6e6177732e636f6d2f67682d6173736574732e63686174776f6f742e636f6d2f6272616e642e737667
    version: 2.0
    source: https://github.com/chatwoot/chatwoot
    tags: customer engagement, customer support, chatbot, omnichannel, CRM, helpdesk, livechat, ticketing, socialmedia, teamcollaboration
  runnable-list:
    - chatwoot/chatwoot-rds
    - chatwoot/chatwoot-db
    - chatwoot/chatwoot-rails
    - chatwoot/chatwoot-sidekiq
  variables:
    chatwoot_secret_key:
      type: string
      value: replace_with_lengthy_secure_hex
    chatwoot_frontend_url:
      type: string
      value: http://0.0.0.0:3000
    chatwoot_helpcenter_url:
      type: string
      value: http://0.0.0.0:3000
    chatwoot_default_locale:
      type: string
      value: en
    chatwoot_asset_cdn:
      type: string
      value: ''
    chatwoot_force_ssl:
      type: bool
      value: false
    chatwoot_enable_account:
      type: bool
      value: false
    chatwoot_redis_password:
      type: string
      value: ''
    chatwoot_redis_sentinels:
      type: string
      value: ''
    chatwoot_redis_sentinels_master:
      type: string
      value: ''
    chatwoot_redis_sentinel_password:
      type: string
      value: ''
    chatwoot_redis_openssl_verify:
      type: string
      value: ''
    chatwoot_database:
      type: string
      value: monk
    chatwoot_database_user:
      type: string
      value: monk
    chatwoot_database_password:
      type: string
      value: monk
    chatwoot_rails_env:
      env: RAILS_ENV
      type: string
      value: <- `${chatwoot_rails_env}`
    chatwoot_rails_max_threads:
      env: RAILS_MAX_THREADS
      type: int
      value: 5
    chatwoot_mail_sender:
      env: MAILER_SENDER_EMAIL
      type: string
      value: Chatwoot <accounts@monk.io>
    chatwoot_smtp_domain:
      env: SMTP_DOMAIN
      type: string
      value: monk.io
    chatwoot_smtp_address:
      type: string
      value: mailhog
    chatwoot_smtp_user:
      type: string
      value: ''
    chatwoot_smtp_password:
      type: string
      value: ''
    chatwoot_smtp_authentication:
      type: string
      value: ''
    chatwoot_enable_starttls_auto:
      type: bool
      value: true
    chatwoot_openssl_verify:
      type: string
      value: peer
    chatwoot_mailer_inbound_email_domain:
      type: string
      value: ''
    chatwoot_rails_inbound_email_service:
      env: RAILS_INBOUND_EMAIL_SERVICE
      type: string
      value: ''
    chatwoot_rails_inbound_email_password:
      env: RAILS_INBOUND_EMAIL_PASSWORD
      type: string
      value: ''
    chatwoot_mailgun_ingress_api_key:
      env: MAILGUN_INGRESS_API_KEY
      type: string
      value: ''
    chatwoot_mandrill_ingress_api_key:
      env: MANDRILL_INGRESS_API_KEY
      type: string
      value: ''
    chatwoot_active_storage_service:
      env: ACTIVE_STORAGE_SERVICE
      type: string
      value: local
    chatwoot_s3_bucket_name:
      env: S3_BUCKET_NAME
      type: string
      value: ''
    chatwoot_aws_access_key_id:
      env: AWS_ACCESS_KEY_ID
      type: string
      value: ''
    chatwoot_aws_secret_access_key:
      env: AWS_SECRET_ACCESS_KEY
      type: string
      value: ''
    chatwoot_aws_region:
      env: AWS_REGION
      type: string
      value: ''
    chatwoot_rails_log_to_stdout:
      env: RAILS_LOG_TO_STDOUT
      type: bool
      value: true
    chatwoot_log_level:
      type: string
      value: info
    chatwoot_log_size:
      type: int
      value: 500
    chatwoot_fb_verify_token:
      type: string
      value: ''
    chatwoot_fb_app_secret:
      type: string
      value: ''
    chatwoot_fb_app_id:
      type: string
      value: ''
    chatwoot_ig_verify_token:
      type: string
      value: ''
    chatwoot_twitter_app_id:
      type: string
      value: ''
    chatwoot_twitter_comsumer_key:
      type: string
      value: ''
    chatwoot_twitter_consumer_secret:
      type: string
      value: ''
    chatwoot_twitter_env:
      type: string
      value: ''
    chatwoot_slack_client_id:
      type: string
      value: ''
    chatwoot_slack_client_secret:
      type: string
      value: ''
    chatwoot_ios_app_id:
      type: string
      value: L7YLMN4634.com.chatwoot.app
    chatwoot_android_bundle_id:
      type: string
      value: com.chatwoot.app
    chatwoot_android_sha256_cert_fingerprint:
      env: ANDROID_SHA256_CERT_FINGERPRINT
      type: string
      value: AC:73:8E:DE:EB:56:EA:CC:10:87:02:A7:65:37:7B:38:D4:5D:D4:53:F8:3B:FB:D3:C6:28:64:1D:AA:08:1E:D8
    chatwoot_use_inbox_avatar_forbot:
      env: USE_INBOX_AVATAR_FOR_BOT
      type: bool
      value: true
    chatwoot_ios_app_identifier:
      env: IOS_APP_IDENTIFIER
      type: string
      value: ''
    chatwoot_enable_push_relay_server:
      env: ENABLE_PUSH_RELAY_SERVER
      type: bool
      value: <- `${chatwoot_enable_push_relay_server}`
    chatwoot_stripe_secret_key:
      env: STRIPE_SECRET_KEY
      type: string
      value: ''
    chatwoot_stripe_webhook_secret:
      env: STRIPE_WEBHOOK_SECRET
      type: string
      value: ''
    chatwoot_direct_uploads_enabled:
      env: DIRECT_UPLOADS_ENABLED
      type: bool
      value: true
